config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'create', to: 'messages#create'

  get 'signup', to: 'users#new'
  resource :users, only: [:create]
  
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_secure_password

  validates :name, uniqueness: true, presence: true, length: { minimum: 6, maximum: 40 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  
  def index
    redirect_to login_path if !logged_in?
    @message = Message.create
    @messages = Message.custom_display    
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(whitelisted_messages)
    ActionCable.server.broadcast "ChatroomChannel", mod_message: message_render(message) if message.save
  end

  private
  def whitelisted_messages
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message} )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :logged_in_redirect, only:[:new, :create]

  def new

  end
  
  def create
    user = User.find_by(name:params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.name} !!!"
      redirect_to root_path
    else
      flash.now[:error] = "Log in failed: Check your credentials"
      render 'new'
    end
  end


  def destroy

    user = User.find(session[:user_id]) if session[:user_id]
    session[:user_id] = nil
    flash[:success] = "Bye #{user.name}. See you soon!!!"
    redirect_to login_path
  end

  private
  def logged_in_redirect
    if logged_in?
      user = User.find(session[:user_id]) if session[:user_id]
      flash[:error] = "You are already logged in #{user.name}"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.new(whitelisted_user_params)
    if @user.save      
      flash[:success] = "Welcome #{@user.name}! "      
      session[:user_id] = @user.id            
      redirect_to root_path
    else
      flash.now[:error] = "Sorry #{@user.name}! Sign up failed, because #{@user.errors.messages}"
      render 'new'
    end
  end

  private
  def whitelisted_user_params
    params.require(:user).permit(:name,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui icon center aligned header">
  <i class="comments outline icon"></i>
  What's talking?
</h4>

<div class="ui column grid ">    

    <div class="ui fluid raised card chatbox">   
      <div class="content" id="messages">      
        <div class="ui feed" id="chatroom-feed">
          <%= render @messages %>    
        </div> 
      </div>   
      <div class="extra content">    
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: create_path, remote: true) do |f| %>
          <div class="field">
              <%= f.text_field :body %>
          </div>
          </div>
        <% end %>
      </div>
    </div>

    
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message_content|%>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
      <div class="header">
        <%= message_content %>
      </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
 
<div class="right menu">
  <% if logged_in? %>   
    <%= link_to "Log out", logout_path, class:"ui orange  button", method: :delete %>  
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="ui inverted small menu">
        <div class="ui container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
      <div class="ui container">
      <%= render 'layouts/messages'%>
        <%= yield %>
      </div>
  </body>
</html>

app/views/messages/_message.html.erb
<b><%= message.user.name %></b>: <%= message.body %>
</br>

app/views/users/new.html.erb
<h2 class="ui center aligned header">Signup for MessageMe -  a complete ChatApp</h2>
<h3 class="ui center aligned icon header">
<i class="pencil alternate icon"></i>
  Signup
</h3>

<div class="ui placeholder raised segment">
  
  <%= form_with(model:@user, class:"ui form", local: true) do |form| %>


    <div class="required field">
      <%= form.label :Username %>         
      <%= form.text_field :name%>             
    </div>

    <div class="required field">
      <%= form.label :Password %>  
      <%= form.password_field :password %>           
    </div>

    <%= form.submit "Sign up", class:"ui orange medium button" %>
    
  <% end %>

</div>